name: Create Release Branch

on:
  workflow_call:
    inputs:
      version:
        description: 'Semantic version number (e.g., 0.0.1)'
        required: true
        type: string

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate version format
        id: validate_version
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "## Validation Report" > report.md
            echo "" >> report.md
            echo "### :x: Invalid version format" >> report.md
            echo "Please use semantic versioning (e.g., 0.0.1)." >> report.md
            exit 1
          else
            echo "## Validation Report" > report.md
            echo "" >> report.md
            echo "### :white_check_mark: Version format is valid" >> report.md
          fi

      - name: Upload validation report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: validation-report
          path: report.md

      - name: Create release branch
        id: create_branch
        run: |
          BRANCH_NAME="release/v${{ inputs.version }}"
          git checkout -b $BRANCH_NAME

      - name: Update version in gradle.properties
        run: |
          sed -i "s/^version=.*/version=${{ inputs.version }}/" gradle.properties
          git add gradle.properties
          git commit -m "Update version to ${{ inputs.version }}"
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}