name: Create Release Tag from gradle.properties

on:
  workflow_call:
jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Get version from  gradle.properties
        id: read-version
        run: |
          VERSION=$(grep -oP 'version=\K.*' gradle.properties)
          echo "Versão encontrada: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Gerar Timestamp
        id: timestamp
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          TAG_MESSAGE="Version ${{ steps.read-version.outputs.version }} created at ${{ steps.timestamp.outputs.timestamp }}"
          git tag -a "${{ steps.read-version.outputs.version }}" -m "$TAG_MESSAGE"
          git push origin " ${{ steps.read-version.outputs.version }}"