name: Generate Repository from lib-template

on:
  workflow_dispatch:
    inputs:
      artifact-id:
        description: 'Nome do repositório a ser criado'
        required: true

jobs:
  generate-repo:
    runs-on: ubuntu-latest

    steps:          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Validate repository existence
        id: validate-repo
        run: |
          REPO_EXISTS=$(gh repo view "${{ github.repository_owner }}/${{ inputs.artifact-id }}" --json name -q '.name' 2>/dev/null || echo "false")
          if [ "$REPO_EXISTS" != "false" ]; then
            echo "::error::Repositório ${{ inputs.artifact-id }} já existe na organização."
            exit 1
          fi

      - name: Create new repository from template
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh repo create "${{ github.repository_owner }}/${{ inputs.artifact-id }}" --template "${{ github.repository_owner }}/lib-template" --private

      - name: Pause for 5 seconds
        run: sleep 5 
      
      - name: Clone the new repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh repo clone "${{ github.repository_owner }}/${{ inputs.artifact-id }}"
          
      - name: Update ArtifactId in gradle.properties
        working-directory: ${{ inputs.artifact-id }}
        run: |
          sed -i "s/artifactId=.*/artifactId=${{ inputs.artifact-id }}/" gradle.properties

      - name: Commit and push changes
        working-directory: ${{ inputs.artifact-id }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "CEG Github"
          git config --global user.email "ceg_ghb@outlook.com"
          git add .
          git commit -m "Update group-id and artifact-id to ceg.lib and ${{ inputs.artifact-id }}"
          git push origin master
