name: Lib CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - release/v**
jobs:
  Setup Pipeline:
    runs-on: ubuntu-latest
    id: setup-pipeline
    outputs:
      gadle-cache-key: ${{ steps.cache-gradle.outputs.cache-key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Gradlew Cache Key
        id: create-gradlew-cache-key
        run: echo "::set-output name=gadle-cache-key::gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}"
      
      - name: Setup Java Environment
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
        if: ${{ steps.cache-gradle.outputs.cache-hit != 'true' }}
      
      - name: Compile gradle files
        run: node .github/actions/global-actions/components/compile.js
      
      - name: Caches Gradle files
        uses: actions/cache@v4
        id: cache-gradle
        with:
          key: ${{ steps.create-gradlew-cache-key.outputs.gradle-cache-key }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          restore-keys: |
            ${{ runner.os }}-gradle-
        

  Run Tests:
    runs-on: ubuntu-latest
    needs: Setup Pipeline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Restores Gradle Cache
        uses: actions/cache@v4
        with:
          key: $ {{ needs.setup-pipeline.outputs.gradle-cache-key }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Tests with Gradle
        run: ./gradlew test
  Publish:
    runs-on: ubuntu-latest
    needs: setup-pipeline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Restores Gradle Cache
        uses: actions/cache@v4
        with:
          key: $ {{ needs.setup-pipeline.outputs.gradle-cache-key }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish with Gradle
        run: ./gradlew publish
              
  Create PR:
    runs-on: ubuntu-latest
    needs: [publish, run-tests]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Merge from ${{ github.ref_name }}"
          branch: ${{ github.ref_name }}
          base: master
          title: "Merge from ${{ github.ref_name }}"
          body: "This PR merges changes from ${{ github.ref_name }} to master."

        