name: Lib CI Pipeline

on:
  workflow_call:
  push:
    branches:
      - release/v**
jobs:
  setup-pipeline:
    runs-on: ubuntu-latest
    outputs:
      gradle-cache-key: ${{ steps.cache-gradle.outputs.cache-key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Gradlew Cache Key
        id: create-gradlew-cache-key
        run: echo "gradle-cache-key=gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}" >> $GITHUB_ENV      
      
      - name: Setup Java Environment
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      
      - name: Caches Gradle files
        uses: actions/cache@v4
        id: cache-gradle
        with:
          key: ${{ env.gradle-cache-key }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Debug Gradle Cache Key
        run: echo "Cache Key: ${{ env.gradle-cache-key }}"

      - name: Compile gradle files
        run: './gradlew assemble'
      
      
        

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-pipeline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug Gradle Cache Key
        run: echo "Cache Key -> ${{ env.gradle-cache-key }}"
      
      - name: Restores Cached Gradle Files
        uses: actions/cache@v4
        id: cache-gradle
        with:
          key: ${{ env.gradle-cache-key }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Tests with Gradle
        run: ./gradlew test
  publish:
    runs-on: ubuntu-latest
    needs: setup-pipeline
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug Gradle Cache Key
        run: echo "Cache Key -> ${{ env.gradle-cache-key }}"

      - name: Restores Cached Gradle Files
        uses: actions/cache@v4
        id: cache-gradle
        with:
          key: ${{ env.gradle-cache-key }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish with Gradle
        run: ./gradlew publish

  create-pr:
    runs-on: ubuntu-latest
    needs: [publish, run-tests]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Merge from ${{ github.ref_name }}"
          branch: ${{ github.ref_name }}
          base: master
          title: "Merge from ${{ github.ref_name }}"
          body: "This PR merges changes from ${{ github.ref_name }} to master."

        